### ISSUE TITLE
[PR]-[BUG]-[SinglyLinkedList]

### ISSUE THREAD

**Issue by eventually-delete** [code-chaser/ds-cpp#2]
There was a fatal error when trying to run "make singlyLinedList" due to typo.
![Screenshot from 2022-10-02 16-36-27](https://user-images.githubusercontent.com/92840840/193459771-6f44efd6-caef-4546-930a-96fb07d21aaa.png)

**Comment by eventually-delete** [comment]
There was also no build folder where to create the executable from the Makefile instructions.

![Screenshot from 2022-10-02 16-40-29](https://user-images.githubusercontent.com/92840840/193460033-8187327c-e14e-4113-ac75-3bc72953a89d.png)

**Comment by code-chaser** [comment]
- Closed in #3
